### ISSUE TITLE
player invis not working

### ISSUE THREAD

**Issue by onycius** [fill1890/FabSit#7]
for /lay and /spin, the original player's model does not turn invisible like it should.
this is on the latest 1.19 version for fabric

**Comment by fill1890** [comment]
Is it player armor showing? If so it's shown to the player posing but not other players, which was intentional but I will change soon

If the actual player isn't hidden, is there any chance you could attach a screenshot and explain what happens? I couldn't find an issue on my test server but I might have missed something

**Comment by onycius** [comment]
[https://cdn.discordapp.com/attachments/984851464604246036/998807082335748146/2022-07-18_23.21.55.png](url)

[https://cdn.discordapp.com/attachments/984851464604246036/998807650949156894/2022-07-18_23.24.38.png](url)

It looks like this for everyone looking at the player

**Comment by fill1890** [comment]
It think it's because you're all on the same team, and by default Minecraft allows you to see invisible players on your own team

I'll write a fix for it and release an updated version, but in the meantime you should be able to fix it on your server by running `/team modify [teamName] seeFriendlyInvisibles false` if you don't need to see invisible players otherwise

Thanks for bringing it up! I didn't know it actually did that to be honest, let me know if the command doesn't fit it :)

**Comment by onycius** [comment]
Just some more info--
I ran the team modify command and it still occurs I think. The player briefly turns invisible then reappears.

[https://cdn.discordapp.com/attachments/984557068688175124/998824670600118402/unknown.png](url)

**Comment by fill1890** [comment]
Weird

Should be resolved in version 1.4.0 which I'll publish in a moment, feel free to reopen the ticket if it keeps happening
